import Head from 'next/head'

export default function Home() {

  function handleClick(event) {
    fetch('http://localhost:3000/api/hello')
      .then((response) => response.json())
      .then((data) => alert(JSON.stringify(data, null, 2)));
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Webapp with Next.js & Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-center p-2 border-b border-primary">

        <h1 className="text-3xl font-bold text-primary">
          Webapp with Next.js & Tailwind CSS
        </h1>
      </header>

      <main className="flex flex-1 flex-col justify-center items-center gap-4">

        <button className="button" onClick={handleClick}>Call example Api-Route</button>
        <a target="_blank" rel="noreferrer" href="https://nextjs.org/docs/getting-started" className="link">Next.js Documentation</a>
        <a target="_blank" rel="noreferrer" href="https://nextjs.org/docs/api-routes/introduction" className="link">Api-Routes Documentation</a>

      </main>

      <footer className="flex justify-center p-2 border-t border-primary h-12">
        <p>This is a footer</p>
      </footer>
    </div>
  )
}
